[project]
name = "ocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.117.1",
    "pillow>=11.3.0",
    "pytesseract>=0.3.13",
    "uvicorn>=0.37.0",
]
